
extensions  = { "c", "cpp", "h" }
cd_root     = true
build       = "cmake -S . -B build && cmake --build build"
run         = "cmake -S . -B build && cmake --build build; ./bin"
clean       = "rm -rf build/*"
debug       = "lldb"

